services:
   app:
      image: vonproteus/record-web-radio-to-podcast
      build:
         context: ./
         dockerfile: Dockerfile
      environment:
         - WRURL=https://web.radio.stream/mp3
         - RECORD_TIME_IN_SECONDS=5
      volumes:
#         - ./test/:/data/
         - testVolume:/data/

networks:
   external:

volumes:
   testVolume:

### Environment variables
